# Generated by Django 3.2.9 on 2021-11-30 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=50, unique=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Defi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeoRun.runner')),
            ],
        ),
    ]
