# Generated by Django 3.2.10 on 2022-02-03 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoRun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude', models.IntegerField(default=0)),
                ('distance', models.IntegerField(default=0)),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeoRun.defi')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeoRun.runner')),
            ],
        ),
    ]
