# Generated by Django 3.2.10 on 2022-02-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoRun', '0002_participation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('participant', 'defi')},
        ),
    ]
