# Generated by Django 3.2.10 on 2022-02-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoRun', '0004_participation_resultats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='resultats',
            field=models.TextField(default=''),
        ),
    ]
