# Generated by Django 3.2.10 on 2022-02-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoRun', '0005_alter_participation_resultats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='altitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='resultats',
            field=models.TextField(null=True),
        ),
    ]
