# Generated by Django 3.2.10 on 2022-02-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoRun', '0006_auto_20220203_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='altitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participation',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
