# Generated by Django 3.2.10 on 2022-02-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoRun', '0007_auto_20220203_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='resultats',
        ),
    ]
