# Generated by Django 3.2.10 on 2022-02-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoRun', '0008_remove_participation_resultats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defi',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='distance',
        ),
        migrations.AddField(
            model_name='defi',
            name='description',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defi',
            name='duree',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defi',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participation',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
