# Generated by Django 3.2.10 on 2022-02-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoRun', '0009_auto_20220215_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
